name: Test Application and Build Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.11
        uses: actions/setup-go@v2
        with:
          go-version: ^1.11
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test project
        run: go test -v .

  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2.3.4

      - name: Build an image from Dockerfile
        run: docker build -t odi2357/demo:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'odi2357/demo:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Declare commmit hash variable
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo:latest, ${{ secrets.DOCKERHUB_USERNAME }}/demo:${{ steps.vars.outputs.sha_short }}